package minesweeper.ai;

import java.util.ArrayList;

import minesweeper.model.Brain;
import minesweeper.boardgame.MineSweeper;

public class Ann {

	protected final int SIZE_OUTPUT = 4;
	
	private Brain brain;
	private ArrayList<Integer> layers = new ArrayList<Integer>();

		
	/***
	 * Create an Artificial Neural Network based on a given boardgame.
	 * The ANN will have 1 input neuron per boardgame box and 4 output neurons.
	 * Hidden layers are generated by dividing the numbers of neuron of the preceding layer by 2.
	 * @param board
	 */
	public Ann(MineSweeper board) {
		int boardSize = board.getSquaredSize();
		int currentNeuronNbr = boardSize*boardSize;
		
		do {
			layers.add(currentNeuronNbr);
			currentNeuronNbr = currentNeuronNbr / 2;
		} while (currentNeuronNbr > 4);
		
		layers.add(SIZE_OUTPUT);
		
		brain = new Brain(layers);
	}
	
	public String toString() {
		return brain.toString();
	}
	
}
